version: '3.7'

volumes:
  nasa_db:
    name: nasa_db

networks:
  default:
    name: nasa
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.7.0/24

services:
  web:
    image: nginx:latest
    container_name: nasa-web
    environment:
      - NGINX_HOST=nasa.local
      - NGINX_PORT=80
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./app:/app
    networks:
      default:
        ipv4_address: 172.22.7.42
        aliases:
          - nasa.local
    expose:
      - 80
      - 443
    links:
      - php74

  php74:
    build:
      context: .
      dockerfile: php74.dockerfile
      args:
        uid: ${UID}
        user: ${USER}
    container_name: nasa-php74
    environment:
      - TIMEZONE=${TIMEZONE}
    volumes:
      - ./app:/app
    networks:
      - default
    expose:
      - 9000
    links:
      - db

  db:
    image: mysql
    container_name: nasa-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - nasa_db:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.22.7.43
        aliases:
          - db.nasa.local
    expose:
      - 3306
